/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_Petugas.java
 *
 * Created on Jan 12, 2017, 6:33:10 PM
 */
package du_rentalmobil.form;
//Import Javax
import javax.swing.*;
//Import Koneksi Database
import java.sql.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author SuryanaMcCarley
 */
public class frm_Petugas extends javax.swing.JInternalFrame {
    du_rentalmobil.koneksi.koneksiRental dbsetting;
    String driver,database,user,pass;
    Object tabel;
    /** Creates new form frm_Petugas */
    public frm_Petugas() {
        initComponents();
        
        dbsetting = new du_rentalmobil.koneksi.koneksiRental();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        
        
        tbl_petugas.setModel(tableModel);
        settableload();
    }
    
    public void membersihkan_teks() {
        id_petugas.setText("");
        nm_petugas.setText("");
        pass_petugas.setText("");     
    }
    
    public void nonaktif_teks() {
        id_petugas.setEnabled(false);
        nm_petugas.setEnabled(false);
        pass_petugas.setEnabled(false);
    }
    
    public void aktif_teks() {
        id_petugas.setEnabled(true);
        nm_petugas.setEnabled(true);
        pass_petugas.setEnabled(true);
    }
    
  
    private javax.swing.table.DefaultTableModel tableModel= getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel getDefaultTabelModel()        
    {
        return new javax.swing.table.DefaultTableModel
                (
                    new Object[][] {},
                    new String[] {"ID Petugas", "Nama Petugas", "Password"}
                )
    {
        boolean[] canEdit = new boolean[] {
            false, false, false
        };
        
       @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
       return canEdit[columnIndex];
        }
     };
   }
    
     String data[]= new String[3];
     private void settableload() {
           String stat = "";
           try {
               Class.forName(driver);
                       Connection kon = (Connection) DriverManager.getConnection(database,user,pass);      
                       
                       Statement stt=(Statement) kon.createStatement();
                       String SQL = "select * from tabel_petugas";
                       ResultSet res = stt.executeQuery(SQL);
                       while(res.next()) {
                        data[0] = res.getString(1); 
                        data[1] = res.getString(2); 
                        data[2] = res.getString(3); 
                        
                        tableModel.addRow(data);
                       }
                       res.close();
                       stt.close();
                       kon.close();
           } catch(Exception ex) {
                           System.err.println(ex.getMessage());
                           JOptionPane.showMessageDialog(null,ex.getMessage(),"Gagal Terhubung Ke Database",JOptionPane.INFORMATION_MESSAGE);
                       }
       }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_petugas = new javax.swing.JTextField();
        nm_petugas = new javax.swing.JTextField();
        pass_petugas = new javax.swing.JTextField();
        simpan_petugas = new javax.swing.JButton();
        ubah_petugas = new javax.swing.JButton();
        hapus_petugas = new javax.swing.JButton();
        batal_petugas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_petugas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Petugas"));

        jLabel1.setText("Id Petugas");

        jLabel2.setText("Nama Petugas");

        jLabel3.setText("Password");

        id_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_petugasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(nm_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(id_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nm_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pass_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpan_petugas.setText("SIMPAN");
        simpan_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_petugasActionPerformed(evt);
            }
        });

        ubah_petugas.setText("UBAH");
        ubah_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_petugasActionPerformed(evt);
            }
        });

        hapus_petugas.setText("HAPUS");
        hapus_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_petugasActionPerformed(evt);
            }
        });

        batal_petugas.setText("BATAL");
        batal_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_petugasActionPerformed(evt);
            }
        });

        tbl_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_petugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_petugas);

        jButton1.setText("SELESAI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan_petugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ubah_petugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus_petugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batal_petugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {batal_petugas, hapus_petugas, jButton1, simpan_petugas, ubah_petugas});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan_petugas)
                    .addComponent(ubah_petugas)
                    .addComponent(hapus_petugas)
                    .addComponent(batal_petugas)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_petugasActionPerformed
        String data[]=new String[3];

        
        if (nm_petugas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong, Silahkan dilengkapi");
            nm_petugas.requestFocus();
        } else {
        try {
         Class.forName(driver);
         Connection kon = (Connection) DriverManager.getConnection(database, user, pass);
         Statement stt = (Statement) kon.createStatement();
         String SQL = "INSERT INTO tabel_petugas (ID_Petugas,"
                                                       + "Nama_Petugas,"
                                                       + "Password)" 
                                                       + "VALUES" 
                                                       + "('"+id_petugas.getText()+"',"                
                                                       + "'"+nm_petugas.getText()+"',"
                                                       + "'"+pass_petugas.getText()+"')";
                      stt.executeUpdate(SQL);
                      data[0]  = id_petugas.getText();                     
                      data[1]  = nm_petugas.getText();
                      data[2]  = pass_petugas.getText();

                      tableModel.setRowCount(0);
                      settableload();
                      stt.close();
                      kon.close();
                      membersihkan_teks();
                      simpan_petugas.setEnabled(true);
                      ubah_petugas.setEnabled(true);
                      hapus_petugas.setEnabled(true);
                      batal_petugas.setEnabled(true);
                      
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Gagal Terhubung Ke Database", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_simpan_petugasActionPerformed

    int row = 0;
    public void tampil_Petugas() {
        row = tbl_petugas.getSelectedRow();
        
        id_petugas.setText(tableModel.getValueAt(row, 0).toString());
        nm_petugas.setText(tableModel.getValueAt(row, 1).toString());
        pass_petugas.setText(tableModel.getValueAt(row, 2).toString());
      
      ubah_petugas.setEnabled(true);  
      hapus_petugas.setEnabled(true);
      simpan_petugas.setEnabled(true);    
     }
    
    private void ubah_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_petugasActionPerformed
        int  ubah= JOptionPane.showConfirmDialog(null,"Apakah anda ingin Mengubah data ini?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(ubah==JOptionPane.YES_OPTION) {
                
            String IdPet  = id_petugas.getText();
            String NmPet  = nm_petugas.getText();
            String passPet = pass_petugas.getText();
          
        if ((NmPet.isEmpty()) || (passPet.isEmpty())){
            JOptionPane.showMessageDialog(null,"Data Tidak Boleh Kosong, Slilahkan Dilengkapi");
            nm_petugas.requestFocus();
        } else {
            try {
                    Class.forName(driver);
                    Connection kon = (Connection) DriverManager.getConnection(database,user, pass);
                    Statement stt = (Statement) kon.createStatement();
                    String SQL = "UPDATE `tabel_petugas` "
                                    + "SET `ID_Petugas`= '"+IdPet+"',"
                                    + "`Nama_Petugas`= '"+NmPet+"',"
                                    + "`Password`= '"+passPet+"'"
                            + "WHERE "
                            + "`ID_Petugas`='"+tableModel.getValueAt(row, 0).toString()+"';";
                    stt.executeUpdate(SQL);
                    data[0] = IdPet;
                    data[1] = NmPet;
                    data[2] = passPet;
                    
                    tableModel.removeRow(row);
                    tableModel.insertRow(row, data);
                    stt.close();
                    kon.close();
                    tbl_petugas.clearSelection();

                    tableModel.setRowCount(0);
                    settableload();
                                        
                    membersihkan_teks();
                    simpan_petugas.setEnabled(true);
                    hapus_petugas.setEnabled(true);
                } catch (Exception ex) {
                            System.err.println(ex.getMessage());
            }
        }
            } else if(ubah==JOptionPane.NO_OPTION) {
            batal_petugasActionPerformed(evt);
        }
    }//GEN-LAST:event_ubah_petugasActionPerformed

    private void tbl_petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_petugasMouseClicked
        if(evt.getClickCount() == 1) {
            tampil_Petugas();
        }
    }//GEN-LAST:event_tbl_petugasMouseClicked

    private void batal_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_petugasActionPerformed
        membersihkan_teks();
        simpan_petugas.setVisible(true);
    }//GEN-LAST:event_batal_petugasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();     }//GEN-LAST:event_jButton1ActionPerformed

    private void id_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_petugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_petugasActionPerformed

    private void hapus_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_petugasActionPerformed
          int  hapus= JOptionPane.showConfirmDialog(null,"Apakah anda ingin Menghapus data ini?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(hapus==JOptionPane.YES_OPTION) {
        int baris = tbl_petugas.getSelectedRow();
            if (baris != -1) {
                String idPetugas = tbl_petugas.getValueAt(baris, 0).toString();
                String SQL = "DELETE FROM tabel_petugas WHERE ID_Petugas='"+idPetugas+"'";
                tableModel.removeRow(row);
                membersihkan_teks();
                int status = du_rentalmobil.koneksi.koneksiRental.execute(SQL);
                if (status==1) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error !!", JOptionPane.WARNING_MESSAGE);
            }
        } else if(hapus==JOptionPane.NO_OPTION) {
            batal_petugasActionPerformed(evt);        }
            aktif_teks();
    }//GEN-LAST:event_hapus_petugasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal_petugas;
    private javax.swing.JButton hapus_petugas;
    private javax.swing.JTextField id_petugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nm_petugas;
    private javax.swing.JTextField pass_petugas;
    private javax.swing.JButton simpan_petugas;
    private javax.swing.JTable tbl_petugas;
    private javax.swing.JButton ubah_petugas;
    // End of variables declaration//GEN-END:variables
}
