/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_mobil.java
 *
 * Created on Jan 12, 2017, 8:01:09 PM
 */
package du_rentalmobil.form;
//Import Javax
import javax.swing.*;
//Import Koneksi Database
import java.sql.*;
/**
 *
 * @author SuryanaMcCarley
 */
public class frm_mobil extends javax.swing.JInternalFrame {
    du_rentalmobil.koneksi.koneksiRental dbsetting;
    String driver,database,user,pass;
    Object tabel;
    /** Creates new form frm_mobil */
    public frm_mobil() {
        initComponents();
        dbsetting = new du_rentalmobil.koneksi.koneksiRental();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        
        
        tbl_mobil.setModel(tableModel);
        settableload();
    }
   
    
    public void membersihkan_teks() {
        no_polisi.setText("");
        warna_mobil.setText("");
        merk_mobil.setSelectedItem("-"); 
        type_mobil.setText("");
        harga_mobil.setText("");
    }
    
    public void nonaktif_teks() {
        no_polisi.setEnabled(false);
        warna_mobil.setEnabled(false);
        merk_mobil.setEnabled(false);
        type_mobil.setEnabled(false);
    }
    
    public void aktif_teks() {
        no_polisi.setEnabled(true);
        warna_mobil.setEnabled(true);
        merk_mobil.setEnabled(true);
        type_mobil.setEnabled(true);
    }
    
  
    private javax.swing.table.DefaultTableModel tableModel= getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel getDefaultTabelModel()        
    {
        return new javax.swing.table.DefaultTableModel
                (
                    new Object[][] {},
                    new String[] {"No Polisi", "Warna Mobil", "Merk Mobil", "Type Mobil","Harga/hari"}
                )
    {
        boolean[] canEdit = new boolean[] {
            false, false, false, false, false
        };
        
       @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
       return canEdit[columnIndex];
        }
     };
   }
    
     String data[]= new String[5];
     private void settableload() {
           String stat = "";
           try {
               Class.forName(driver);
                       Connection kon = (Connection) DriverManager.getConnection(database,user,pass);      
                       
                       Statement stt=(Statement) kon.createStatement();
                       String SQL = "select * from tabel_mobil";
                       ResultSet res = stt.executeQuery(SQL);
                       while(res.next()) {
                        data[0] = res.getString(1); 
                        data[1] = res.getString(2); 
                        data[2] = res.getString(3);
                        data[3] = res.getString(4); 
                        data[4] = res.getString(5); 
                        
                        tableModel.addRow(data);
                       }
                       res.close();
                       stt.close();
                       kon.close();
           } catch(Exception ex) {
                           System.err.println(ex.getMessage());
                           JOptionPane.showMessageDialog(null,ex.getMessage(),"Gagal Terhubung Ke Database",JOptionPane.INFORMATION_MESSAGE);
                       }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no_polisi = new javax.swing.JTextField();
        warna_mobil = new javax.swing.JTextField();
        type_mobil = new javax.swing.JTextField();
        merk_mobil = new javax.swing.JComboBox();
        laleb = new javax.swing.JLabel();
        harga_mobil = new javax.swing.JTextField();
        simpan_mobil = new javax.swing.JButton();
        ubah_mobil = new javax.swing.JButton();
        hapus_mobil = new javax.swing.JButton();
        batal_mobil = new javax.swing.JButton();
        selesai_mobil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_mobil = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mobil"));

        jLabel1.setText("Nomor Polisi");

        jLabel2.setText("Warna Mobil");

        jLabel3.setText("Merk Mobil");

        jLabel4.setText("Type Mobil");

        no_polisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_polisiActionPerformed(evt);
            }
        });

        warna_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warna_mobilActionPerformed(evt);
            }
        });

        type_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_mobilActionPerformed(evt);
            }
        });

        merk_mobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Isuzu", "Honda", "Toyota", "Suzuki", "Mitsubishi", "Daihatsu", "Mazda" }));
        merk_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merk_mobilActionPerformed(evt);
            }
        });

        laleb.setText("Harga");

        harga_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_mobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(laleb))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(harga_mobil, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(type_mobil, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(warna_mobil, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(merk_mobil, 0, 279, Short.MAX_VALUE)
                    .addComponent(no_polisi, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(no_polisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(warna_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(merk_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(type_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laleb)
                    .addComponent(harga_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpan_mobil.setText("SIMPAN");
        simpan_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_mobilActionPerformed(evt);
            }
        });

        ubah_mobil.setText("UBAH");
        ubah_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_mobilActionPerformed(evt);
            }
        });

        hapus_mobil.setText("HAPUS");
        hapus_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_mobilActionPerformed(evt);
            }
        });

        batal_mobil.setText("BATAL");
        batal_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_mobilActionPerformed(evt);
            }
        });

        selesai_mobil.setText("SELESAI");
        selesai_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesai_mobilActionPerformed(evt);
            }
        });

        tbl_mobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_mobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mobilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_mobil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan_mobil)
                        .addGap(10, 10, 10)
                        .addComponent(ubah_mobil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus_mobil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batal_mobil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(selesai_mobil)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {batal_mobil, hapus_mobil, selesai_mobil, simpan_mobil, ubah_mobil});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubah_mobil)
                    .addComponent(hapus_mobil)
                    .addComponent(batal_mobil)
                    .addComponent(selesai_mobil)
                    .addComponent(simpan_mobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_polisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_polisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_polisiActionPerformed

    private void warna_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warna_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warna_mobilActionPerformed

    private void type_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_mobilActionPerformed

    private void merk_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merk_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merk_mobilActionPerformed

    private void simpan_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_mobilActionPerformed
        String data[]=new String[5];

        if (warna_mobil.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong, Silahkan dilengkapi");
            warna_mobil.requestFocus();
        } else {
        try {
         Class.forName(driver);
         Connection kon = (Connection) DriverManager.getConnection(database, user, pass);
         Statement stt = (Statement) kon.createStatement();
         String SQL = "INSERT INTO tabel_mobil (No_Polisi,"
                                                       + "Warna_Mobil,"
                                                       + "Merk_Mobil,"
                                                       + "Type_mobil,"
                                                       + "Harga)"
                                                       + "VALUES" 
                                                       + "('"+no_polisi.getText()+"',"                
                                                       + "'"+warna_mobil.getText()+"',"
                                                       + "'"+merk_mobil.getSelectedItem().toString()+"',"
                                                       + "'"+type_mobil.getText()+"',"
                                                       + "'"+harga_mobil.getText()+"')";
                      stt.executeUpdate(SQL);
                      data[0]  = no_polisi.getText();                     
                      data[1]  = warna_mobil.getText();
                      data[2]  = merk_mobil.getSelectedItem().toString();
                      data[3]  = type_mobil.getText();
                      data[4]  = harga_mobil.getText();

                      tableModel.setRowCount(0);
                      settableload();
                      stt.close();
                      kon.close();
                      membersihkan_teks();
                      simpan_mobil.setEnabled(true);
                      ubah_mobil.setEnabled(true);
                      hapus_mobil.setEnabled(true);
                      batal_mobil.setEnabled(true);
                      
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Gagal Terhubung Ke Database", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    int row = 0;
    public void tampil_mobil() {
        row = tbl_mobil.getSelectedRow();
        
        no_polisi.setText(tableModel.getValueAt(row, 0).toString());
        warna_mobil.setText(tableModel.getValueAt(row, 1).toString());
        merk_mobil.setSelectedItem(tableModel.getValueAt(row, 2).toString());
        type_mobil.setText(tableModel.getValueAt(row, 3).toString());
        harga_mobil.setText(tableModel.getValueAt(row, 4).toString());
      
      ubah_mobil.setEnabled(true);  
      hapus_mobil.setEnabled(true);
      simpan_mobil.setEnabled(true);    
     
    }//GEN-LAST:event_simpan_mobilActionPerformed

    private void tbl_mobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mobilMouseClicked
       if(evt.getClickCount() == 1) {
            tampil_mobil();
    }//GEN-LAST:event_tbl_mobilMouseClicked
    }
        private void ubah_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_mobilActionPerformed
        int  ubah= JOptionPane.showConfirmDialog(null,"Apakah anda ingin Mengubah data ini?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(ubah==JOptionPane.YES_OPTION) {
                
            String NoPol  = no_polisi.getText();
            String WarMob  = warna_mobil.getText();
            String MerMob = merk_mobil.getSelectedItem().toString();
            String TyeMob = type_mobil.getText();
            String HargMo = harga_mobil.getText();
          
        if ((WarMob.isEmpty()) || (MerMob.isEmpty())){
            JOptionPane.showMessageDialog(null,"Data Tidak Boleh Kosong, Slilahkan Dilengkapi");
            warna_mobil.requestFocus();
        } else {
            try {
                    Class.forName(driver);
                    Connection kon = (Connection) DriverManager.getConnection(database,user, pass);
                    Statement stt = (Statement) kon.createStatement();
                    String SQL = "UPDATE `tabel_mobil` "
                                    + "SET `No_Polisi`= '"+NoPol+"',"
                                    + "`Warna_Mobil`= '"+WarMob+"',"
                                    + "`Merk_Mobil`= '"+MerMob+"',"
                                    + "`Type_Mobil`= '"+TyeMob+"',"
                                    + "`Harga`= '"+HargMo+"'"
                            + "WHERE "
                            + "`No_Polisi`='"+tableModel.getValueAt(row, 0).toString()+"';";
                    stt.executeUpdate(SQL);
                    data[0] = NoPol;
                    data[1] = WarMob;
                    data[2] = MerMob;
                    data[3] = TyeMob;
                    data[4] = HargMo;
                    
                    tableModel.removeRow(row);
                    tableModel.insertRow(row, data);
                    stt.close();
                    kon.close();
                    tbl_mobil.clearSelection();

                    tableModel.setRowCount(0);
                    settableload();
                                        
                    membersihkan_teks();
                    simpan_mobil.setEnabled(true);
                    hapus_mobil.setEnabled(true);
                } catch (Exception ex) {
                 System.err.println(ex.getMessage());
            }
         }
            } else if(ubah==JOptionPane.NO_OPTION) {
            batal_mobilActionPerformed(evt);
        }
    }//GEN-LAST:event_ubah_mobilActionPerformed

    private void batal_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_mobilActionPerformed
        membersihkan_teks();
        simpan_mobil.setVisible(true);
    }//GEN-LAST:event_batal_mobilActionPerformed

    private void hapus_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_mobilActionPerformed
        int  hapus= JOptionPane.showConfirmDialog(null,"Apakah anda ingin Menghapus data ini?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(hapus==JOptionPane.YES_OPTION) {
        int baris = tbl_mobil.getSelectedRow();
            if (baris != -1) {
                String nopolisi = tbl_mobil.getValueAt(baris, 0).toString();
                String SQL = "DELETE FROM tabel_mobil WHERE No_Polisi='"+nopolisi+"'";
                tableModel.removeRow(row);
                membersihkan_teks();
                int status = du_rentalmobil.koneksi.koneksiRental.execute(SQL);
                if (status==1) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error !!", JOptionPane.WARNING_MESSAGE);
            }
        } else if(hapus==JOptionPane.NO_OPTION) {
            batal_mobilActionPerformed(evt);        }
            aktif_teks();
    }//GEN-LAST:event_hapus_mobilActionPerformed

    private void selesai_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesai_mobilActionPerformed
        this.dispose();     
    }//GEN-LAST:event_selesai_mobilActionPerformed

    private void harga_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_mobilActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal_mobil;
    private javax.swing.JButton hapus_mobil;
    private javax.swing.JTextField harga_mobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel laleb;
    private javax.swing.JComboBox merk_mobil;
    private javax.swing.JTextField no_polisi;
    private javax.swing.JButton selesai_mobil;
    private javax.swing.JButton simpan_mobil;
    private javax.swing.JTable tbl_mobil;
    private javax.swing.JTextField type_mobil;
    private javax.swing.JButton ubah_mobil;
    private javax.swing.JTextField warna_mobil;
    // End of variables declaration//GEN-END:variables
}
