/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * halamanUtama.java
 *
 * Created on Jan 12, 2017, 5:40:30 PM
 */
package du_rentalmobil.form;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author SuryanaMcCarley
 */
public class halamanUtama extends javax.swing.JFrame {
    du_rentalmobil.koneksi.koneksiRental dbsetting;
    String driver,database,user,pass;
    int i = 0;
    Boolean login=false;
    String userakses;
    String kode;

    /** Creates new form halamanUtama */
    public halamanUtama() {
     dbsetting = new du_rentalmobil.koneksi.koneksiRental();
     driver = dbsetting.SettingPanel("DBDriver");
     database = dbsetting.SettingPanel("DBDatabase");
     user =  dbsetting.SettingPanel("DBUsername");
     pass =  dbsetting.SettingPanel("DBPassword");
     
     this.setUndecorated(true);
     this.setResizable(false);
     initComponents();
     Toolkit tk = Toolkit.getDefaultToolkit();
     int xsize = (int) tk.getScreenSize().getWidth();
     int ysize = (int) tk.getScreenSize().getHeight();
     this.setSize(xsize, ysize);
     
     
     DekstopMenu.setVisible(false);
     LogOut.setVisible(false);
     UserLogin.setVisible(false);
     sssa.setVisible(false);
     Pengaturan.setVisible(false);
     panPengaturan.setVisible(false);
     settableload();
     
     tabel_bank.setModel(tableModel);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        LogOut = new javax.swing.JButton();
        sssa = new javax.swing.JLabel();
        UserLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Pengaturan = new javax.swing.JButton();
        AksesLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        DekstopMenu = new javax.swing.JDesktopPane();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        panPengaturan = new javax.swing.JPanel();
        selesai_bank = new javax.swing.JButton();
        no_rek = new javax.swing.JTextField();
        nm_bank = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        atas_nama = new javax.swing.JTextField();
        simpan_bank = new javax.swing.JButton();
        ubah_bank = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_bank = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        batal_bank = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnCariBackup = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtLokasiBackup = new javax.swing.JTextField();
        btnBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogOut.setText("Keluar");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        sssa.setText("Selamat Datang,");

        UserLogin.setText("UserLogin");

        jLabel4.setText("0821-2020-0951 / 0857-9491-9151");

        jLabel3.setText("022-91833151 / 022-61121251");

        jLabel2.setText("Jl. Dipati Ukur No.51 Lt.2 RM. Ampera");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("DIPATI UKUR RENTAL MOBIL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        Pengaturan.setText("Pengaturan");
        Pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengaturanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Pengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(sssa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(UserLogin)))
                    .addComponent(LogOut))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LogOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sssa)
                            .addComponent(UserLogin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pengaturan))))
        );

        AksesLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Akses"));

        jLabel5.setText("Username :");

        jLabel6.setText("Password : ");

        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Batal");

        javax.swing.GroupLayout AksesLoginLayout = new javax.swing.GroupLayout(AksesLogin);
        AksesLogin.setLayout(AksesLoginLayout);
        AksesLoginLayout.setHorizontalGroup(
            AksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AksesLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AksesLoginLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AksesLoginLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AksesLoginLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        AksesLoginLayout.setVerticalGroup(
            AksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AksesLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AksesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Penyewaan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(0, 0, 100, 23);
        DekstopMenu.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("Data Mobil");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(100, 0, 90, 23);
        DekstopMenu.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("Data Pelanggan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(190, 0, 120, 23);
        DekstopMenu.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setText("Data Petugas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(310, 0, 110, 23);
        DekstopMenu.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setText("Data Driver");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setBounds(420, 0, 90, 23);
        DekstopMenu.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        panPengaturan.setBorder(javax.swing.BorderFactory.createTitledBorder("Pengaturan"));

        selesai_bank.setText("Selesai");
        selesai_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesai_bankActionPerformed(evt);
            }
        });

        no_rek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_rekActionPerformed(evt);
            }
        });

        jLabel7.setText("No Rek");

        jLabel8.setText("Bank");

        jLabel9.setText("Atas Nama");

        simpan_bank.setText("Simpan");
        simpan_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_bankActionPerformed(evt);
            }
        });

        ubah_bank.setText("Ubah");
        ubah_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_bankActionPerformed(evt);
            }
        });

        tabel_bank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_bank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_bankMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_bank);

        batal_bank.setText("Batal");
        batal_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_bankActionPerformed(evt);
            }
        });

        jLabel12.setText("Pilih File");

        btnCariBackup.setText("Cari");
        btnCariBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBackupActionPerformed(evt);
            }
        });

        jLabel13.setText("Lokasi File");

        btnBackup.setText("Backup");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariBackup))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLokasiBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(btnBackup)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnCariBackup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLokasiBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBackup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Backup db", jPanel3);

        javax.swing.GroupLayout panPengaturanLayout = new javax.swing.GroupLayout(panPengaturan);
        panPengaturan.setLayout(panPengaturanLayout);
        panPengaturanLayout.setHorizontalGroup(
            panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPengaturanLayout.createSequentialGroup()
                .addGroup(panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panPengaturanLayout.createSequentialGroup()
                        .addGroup(panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atas_nama)
                            .addComponent(nm_bank)
                            .addComponent(no_rek, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panPengaturanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(simpan_bank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubah_bank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selesai_bank)
                        .addGap(18, 18, 18)
                        .addComponent(batal_bank))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panPengaturanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panPengaturanLayout.setVerticalGroup(
            panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPengaturanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(no_rek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nm_bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(atas_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan_bank)
                    .addComponent(ubah_bank)
                    .addComponent(selesai_bank)
                    .addComponent(batal_bank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AksesLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DekstopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AksesLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(DekstopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        i=i+1; 
        try
        {
            Class.forName(driver);
            Connection kon = (Connection) DriverManager.getConnection(database,user,pass);
            Statement stt=(Statement) kon.createStatement();
            String SQL = "  SELECT Id_Petugas,Nama_Petugas,Password " +
                    "       FROM tabel_petugas " +
                    "       WHERE Nama_Petugas='"+username.getText().replaceAll("'", "")+"' " +
                    "       AND Password = '"+Password.getText().replaceAll("'", "")+"'";
            ResultSet res = stt.executeQuery(SQL);
            if(res.next()){
                //panggil form
                userakses = res.getString(2) +" "+res.getString(3);
                kode = res.getString(1);
                UserLogin.setText(userakses);

                
                DekstopMenu.setVisible(true); 
                AksesLogin.setVisible(false);
                LogOut.setVisible(true);
                
                login=true;
                UserLogin.setVisible(true);
                sssa.setVisible(true);
                Pengaturan.setVisible(true);
     
            }
            else{
                if((i==1)&&(login==false) ){
                    JOptionPane.showMessageDialog(null,":( Gagal Login, Silahkan Coba Lagi (2).");
                    Password.setText("");
                }
                else if(i == 2){
                    JOptionPane.showMessageDialog(null,":( Gagal Login, Silahkan Coba Lagi (1).");
                    Password.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Maaf, Anda telah gagal login 3 kali, sistem akan keluar");
                    System.exit(0);
                }
            }
        }
        catch(Exception ex)
        {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Gagal Terhubung Ke database",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
       }
    }//GEN-LAST:event_PasswordKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        DekstopMenu.setVisible(false); 
        AksesLogin.setVisible(true);
        LogOut.setVisible(false);
        UserLogin.setVisible(false);
        sssa.setVisible(false);
        username.setText("");
        Password.setText("");
        Pengaturan.setVisible(false); 
        panPengaturan.setVisible(false); 
       
    }//GEN-LAST:event_LogOutActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    frm_Petugas openPan = new frm_Petugas();
    DekstopMenu.add(openPan);
    openPan.show();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frm_mobil openPan = new frm_mobil();
    DekstopMenu.add(openPan);
    openPan.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        frm_pelanggan openPan = new frm_pelanggan();
    DekstopMenu.add(openPan);
    openPan.show();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        frm_driver openPan = new frm_driver();
    DekstopMenu.add(openPan);
    openPan.show();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    frm_penyewaan openPan = null;
        try {
            openPan = new frm_penyewaan(kode);
        } catch (SQLException ex) {
            Logger.getLogger(halamanUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    DekstopMenu.add(openPan);
    openPan.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengaturanActionPerformed
    panPengaturan.setVisible(true);
    }//GEN-LAST:event_PengaturanActionPerformed

    private void selesai_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesai_bankActionPerformed
        panPengaturan.setVisible(false);
    }//GEN-LAST:event_selesai_bankActionPerformed

    private void no_rekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_rekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_rekActionPerformed

    private void simpan_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_bankActionPerformed
          String data[]=new String[4];

        
        if (nm_bank.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong, Silahkan dilengkapi");
            nm_bank.requestFocus();
        } else {
        try {
         Class.forName(driver);
         Connection kon = (Connection) DriverManager.getConnection(database, user, pass);
         Statement stt = (Statement) kon.createStatement();
         String SQL = "INSERT INTO tabel_bank (No_Rek_Rental,"
                                                       + "Bank,"
                                                       + "Atas_Nama_Rek)"
                                                       + "VALUES" 
                                                       + "('"+no_rek.getText()+"',"                
                                                       + "'"+nm_bank.getText()+"',"
                                                       + "'"+atas_nama.getText()+"')";
                      stt.executeUpdate(SQL);
                      data[0]  = no_rek.getText();                     
                      data[1]  = nm_bank.getText();
                      data[2]  = atas_nama.getText();
                     
                      
                      tableModel.setRowCount(0);
                      settableload();
                      stt.close();
                      kon.close();
                      membersihkan_teks();
                      simpan_bank.setEnabled(true);
                      ubah_bank.setEnabled(true);
                      selesai_bank.setEnabled(true);
                      
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Gagal Terhubung Ke Database", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_simpan_bankActionPerformed

    private void ubah_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_bankActionPerformed
    int  ubah= JOptionPane.showConfirmDialog(null,"Apakah anda ingin Mengubah data ini?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(ubah==JOptionPane.YES_OPTION) {
                
            String NoRek  = no_rek.getText();
            String NMBank  = nm_bank.getText();
            String AtasNama = atas_nama.getText();
            
        if ((NoRek.isEmpty()) || (NMBank.isEmpty())){
            JOptionPane.showMessageDialog(null,"Data Tidak Boleh Kosong, Slilahkan Dilengkapi");
            no_rek.requestFocus();
        } else {
            try {
                    Class.forName(driver);
                    Connection kon = (Connection) DriverManager.getConnection(database,user, pass);
                    Statement stt = (Statement) kon.createStatement();
                    String SQL = "UPDATE `tabel_bank` "
                                    + "SET `No_Rek_Rental`= '"+NoRek+"',"
                                    + "`Bank`= '"+NMBank+"',"
                                    + "`Atas_Nama_Rek`= '"+AtasNama+"'"
                                    
                            + "WHERE "
                            + "`No_Rek_Rental`='"+tableModel.getValueAt(row, 0).toString()+"';";
                    
                    stt.executeUpdate(SQL);
                    data[0] = NoRek;
                    data[1] = NMBank;
                    data[2] = AtasNama;
                    
                    tableModel.removeRow(row);
                    tableModel.insertRow(row, data);
                    stt.close();
                    kon.close();
                    tabel_bank.clearSelection();

                    tableModel.setRowCount(0);
                    settableload();
                                
                    membersihkan_teks();
                    simpan_bank.setEnabled(true);
                    
                } catch (Exception ex) {
                            System.err.println(ex.getMessage());
            }
        }
            } else if(ubah==JOptionPane.NO_OPTION) {
            batal_bankActionPerformed(evt);
        }
    }//GEN-LAST:event_ubah_bankActionPerformed

    private void batal_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_bankActionPerformed
     membersihkan_teks();
    }//GEN-LAST:event_batal_bankActionPerformed

    private void btnCariBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBackupActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "sql file", "sql");
        jFileChooser1.setFileFilter(filter);
        int returnVal = jFileChooser1.showSaveDialog(this);
        if(returnVal == jFileChooser1.APPROVE_OPTION) {
            txtLokasiBackup.setText(jFileChooser1.getSelectedFile().getPath()+".sql");
        }
    }//GEN-LAST:event_btnCariBackupActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
       try{
            if(txtLokasiBackup.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Pilih lokasi backup terlebih dahulu");
            } else{
                Process menjalankancmd = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqldump -hlocalhost -uroot du_rentalmobil -r "+txtLokasiBackup.getText());
                int prosesSukses=menjalankancmd.waitFor();
                if(prosesSukses==0){
                    JOptionPane.showMessageDialog(null, "Backup database Sukses");
                } else {
                    JOptionPane.showMessageDialog(null, "Backup database gagal");
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Backup database gagal, Periksa kembali");
        }
    }//GEN-LAST:event_btnBackupActionPerformed

    private void tabel_bankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_bankMouseClicked
        if(evt.getClickCount() == 1) {
            tampil_Bank();
           }
    }//GEN-LAST:event_tabel_bankMouseClicked
    
    int row = 0;
    public void tampil_Bank() {
        row = tabel_bank.getSelectedRow();
        
        no_rek.setText(tableModel.getValueAt(row, 0).toString());
        nm_bank.setText(tableModel.getValueAt(row, 1).toString());
        atas_nama.setText(tableModel.getValueAt(row, 2).toString());
        
      ubah_bank.setEnabled(true);  
      selesai_bank.setEnabled(true);
      simpan_bank.setEnabled(true);
    }
    
    public void membersihkan_teks() {
        no_rek.setText("");
        nm_bank.setText(""); 
        atas_nama.setText("");
    }
    
    public void nonaktif_teks() {
        no_rek.setEnabled(false);
        nm_bank.setEnabled(false);
        atas_nama.setEnabled(false);
    }
    
    public void aktif_teks() {
        no_rek.setEnabled(true);
        nm_bank.setEnabled(true);
        atas_nama.setEnabled(true);
    }
    
    private javax.swing.table.DefaultTableModel tableModel= getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel getDefaultTabelModel()        
    {
        return new javax.swing.table.DefaultTableModel
                (
                    new Object[][] {},
                    new String[] {"No_Rek_Bank", "Bank", "Atas_Nama_Bank"}
                )
    {
        boolean[] canEdit = new boolean[] {
            false, false, false
        };
        
       @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
       return canEdit[columnIndex];
        }
     };
   }
    
     String data[]= new String[4];
     private void settableload() {
           String stat = "";
           try {
               Class.forName(driver);
                       Connection kon = (Connection) DriverManager.getConnection(database,user,pass);      
                       
                       Statement stt=(Statement) kon.createStatement();
                       String SQL = "select * from tabel_bank";
                       ResultSet res = stt.executeQuery(SQL);
                       while(res.next()) {
                        data[0] = res.getString(1); 
                        data[1] = res.getString(2); 
                        data[2] = res.getString(3); 
                        
                        tableModel.addRow(data);
                       }
                       res.close();
                       stt.close();
                       kon.close();
           } catch(Exception ex) {
                           System.err.println(ex.getMessage());
                           JOptionPane.showMessageDialog(null,ex.getMessage(),"Gagal Terhubung Ke Database",JOptionPane.INFORMATION_MESSAGE);
                       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new halamanUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AksesLogin;
    private javax.swing.JDesktopPane DekstopMenu;
    private javax.swing.JButton LogOut;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Pengaturan;
    private javax.swing.JLabel UserLogin;
    private javax.swing.JTextField atas_nama;
    private javax.swing.JButton batal_bank;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnCariBackup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nm_bank;
    private javax.swing.JTextField no_rek;
    private javax.swing.JPanel panPengaturan;
    private javax.swing.JButton selesai_bank;
    private javax.swing.JButton simpan_bank;
    private javax.swing.JLabel sssa;
    private javax.swing.JTable tabel_bank;
    private javax.swing.JTextField txtLokasiBackup;
    private javax.swing.JButton ubah_bank;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

   
}
